// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTL8F_nFh0x9vJFPxZxugxREGAN-Puwr4',
    appId: '1:824776521320:web:7a275ef20eb30684112ddd',
    messagingSenderId: '824776521320',
    projectId: 'iot-project-8339d',
    authDomain: 'iot-project-8339d.firebaseapp.com',
    storageBucket: 'iot-project-8339d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFfLLBWhHvfIkrOuMvLBjM1hJ2_gvnuek',
    appId: '1:824776521320:android:9a57897d45cce8e8112ddd',
    messagingSenderId: '824776521320',
    projectId: 'iot-project-8339d',
    storageBucket: 'iot-project-8339d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1QpE7YzJO9f1Lwsr593-iBM5Ml-ArvVg',
    appId: '1:824776521320:ios:7de51e04c21df335112ddd',
    messagingSenderId: '824776521320',
    projectId: 'iot-project-8339d',
    storageBucket: 'iot-project-8339d.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1QpE7YzJO9f1Lwsr593-iBM5Ml-ArvVg',
    appId: '1:824776521320:ios:7de51e04c21df335112ddd',
    messagingSenderId: '824776521320',
    projectId: 'iot-project-8339d',
    storageBucket: 'iot-project-8339d.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTL8F_nFh0x9vJFPxZxugxREGAN-Puwr4',
    appId: '1:824776521320:web:4a3ed77f25d4ca76112ddd',
    messagingSenderId: '824776521320',
    projectId: 'iot-project-8339d',
    authDomain: 'iot-project-8339d.firebaseapp.com',
    storageBucket: 'iot-project-8339d.appspot.com',
  );
}
